name: Shell Commands 

on: 
  schedule:
    - cron: '0 0 1 * *'

jobs:
  run_shell_command:
    runs-on: ubuntu-20.04
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multi line script 
        run: |
           node -v 
           npm -v
      - name: run python command
        shell: python
        run: |
          import platform
          import sys
          print(platform.processor())
          print(sys.version)
  run_windows_commands:
    runs-on: windows-latest
    needs: run_shell_command
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
