name: Client Payload

on:
  workflow_dispatch:
  repository_dispatch:
    types: ["manual_trigger"]

jobs:
  run_github_actions:
    runs-on: ubuntu-20.04
    steps:
      - name: echo payload
        run: echo ${{ github.event.client_payload.msg }}
