name: Setup/Matrix

on: push

jobs:
  node_version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: 
        node_version: [6,8,10]
    steps:
      - name: Log node version - 1
        run: node -v
      - uses:  actions/setup-node@v2
        with:
          node-version: ${matrix.node_version}
      - name: Log node version - 2
        run: node -v

