name: Setup/Matrix

on: push

jobs:
  node_version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node version - 1
        run: node -v
      - uses:  actions/setup-node@v2
        with:
          node-version: 6
      - name: Log node version - 2
        run: node -v

