name: Containers in Steps

on: push

# on:
#   workflow_dispatch:
#   repository_dispatch:
#     types: ["manual_trigger"]

    
jobs:
  docker_steps:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    steps:
      - name: Log Python Version
        run: python --version
      - name: step with dockers
        uses: docker://python:rc
        with:
          entrypoint: '/bin/echo'
          args: 'Ola'
      - name: step with dockers
        uses: docker://python:rc
        with:
          entrypoint: '/usr/bin/python3'
          args: '--version'
      - name: step with dockers
        uses: docker://python:rc
        with:
          entrypoint: 'python3'
          args: '--version'
      

