name: Containers in Steps

# on: push

on:
  workflow_dispatch:
  repository_dispatch:
    types: ["manual_trigger"]

    
jobs:
  docker_steps:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    
    steps:
    
      - name: python system
        run: python --version

      - name: python3 system
        uses: docker://python:rc
        with:
          entrypoint: '/usr/bin/python3'
          args: '--version'

      - name: python3 3.8
        run: python3 --version

      - name: python3 latest
        uses: docker://python:rc
        with:
          entrypoint: 'python3'
          args: '--version'
      

