name: SCript in Container

on: push

# on:
#   workflow_dispatch:
#   repository_dispatch:
#     types: ["manual_trigger"]

    
jobs:
  docker_steps:
    runs-on: ubuntu-latest
    container:
      image: python:3.8
    
    steps:
      
      - uses: actions/checkout@v1
      
      - name: Check files
        run: ls -al
      
      - name: Make script executable
        run: chmod +x git_action_script.sh
      
      - name: Check files again
        run: ls -al
      
      - name: Run Script
        uses: docker://python:rc
        with:
          entrypoint: ./git_action_script.sh
          args: "'I was here indeed'"

      

