name: Github Actions

on: [push]

jobs:
  run_github_actions:
    runs-on: ubuntu-20.04
    steps:
      - name: simple JS Actions
        id: greet
        uses: petermeissner/hello-world-javascript-action@main
        with:
          who-to-greet: 'Peter'
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: Log Pusher Name
        run: echo "${{ steps.greet.outputs.pusher }}"
