name: Shell Commands 

on: 
  - push
  - issues

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps: 
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script 
        run: |
           node -v 
           npm -v
      - name: run python command
        shell: python3
        run: |
          import platform
          print(platform.processor())
  run_windows_commands:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
